name: finansia_app
description: Modern Personal Finance Management Application.
publish_to: 'none' # Hapus baris ini jika ingin mempublikasikan ke pub.dev nanti

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # --- PACKAGE TAMBAHAN FINANSIA ---
  go_router: ^13.2.0    # Untuk navigasi halaman modern
  flutter_svg: ^2.0.10  # Untuk membaca icon/avatar berformat .svg

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # --- PENDAFTARAN FOLDER ASSETS ---
  assets:
    - assets/images/
    - assets/icons/

  # --- PENDAFTARAN FONT POPPINS ---
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700